//#ifndef CONFIG_HAL_TRANSDUCER_H
//#define CONFIG_HAL_TRANSDUCER_H
//
//#ifdef CONFIG_HAL_TRANSDUCER_MOTOR_FUNCTIONS_USER_DEFINED
//
//#elif defined(CONFIG_HAL_TRANSDUCER_MOTOR_FUNCTIONS_S32K)
//
//#else
//	#define CONFIG_HAL_TRANSDUCER_MOTOR_FUNCTIONS_USER_DEFINED
//#endif
//
//
//#endif
